package CrossData;
import java.io.*;
import java.util.HashMap;
import java.util.Map;
import CrossData.fileAttribute;

public class fileAdd {
	public static void filesAdd(fileAttribute originf,fileAttribute[] addf) {
		String errstr="";
		try {
			
			File outfile = new File(originf.getFolder()+"\\fileAdd");
			if(!outfile.exists()) {
				outfile.mkdir();
			}
			String[] originFields = originf.getFieldList();
			BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(originf.getFilePath()),"UTF-8")); 
			BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(outfile.getAbsolutePath()+"\\"+originf.getFileName()),"UTF-8"));
			 
			String str = "";
			while((str=reader.readLine())!=null) {
				writer.write(str+"\r\n");
			}
			reader.close();
			//add
			System.out.println("read:"+originf.getFilePath());
			Map<Integer,String> placeToField = new HashMap<Integer,String>();
			for(int i=0;i<originFields.length;i++) {//保存原始文件的各字段名对应的位置 int->string
				placeToField.put(i, originFields[i]);
			}
			for(int i=0;i<addf.length;i++) {
				System.out.println("add:"+addf[i].getFilePath());
				String[] fieldslist = addf[i].getFieldList();
				Map<String,Integer> fieldToPlace = new HashMap<String,Integer>();
				//System.out.print(fieldslist.length);
				for(int k=0;k<fieldslist.length;k++) {
					fieldToPlace.put(fieldslist[k], k);//保存要添加的文件的字段位置 string->int
					//System.out.print(fieldslist[k]+",");
				}
				File addfile = new File(addf[i].getFilePath());
				BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(addfile),"UTF-8")); 
				
				while((str = br.readLine())!=null) {
					String[] temp = str.split(addf[i].getFileSeparator());
					if(temp.length<addf[i].getRowLength()-1) {
						continue;
					}
					errstr=str;
					for(int j=0;j<originFields.length;j++) {//原始字段数
						if(fieldToPlace.containsKey(placeToField.get(j))) {//若两者的字段重叠
							writer.write(temp[fieldToPlace.get(placeToField.get(j))]);//根据原始字段位置寻找对应在原始字段名词再找出其在需要添加文件中的位置
						}
						
						if(j!=originFields.length-1) {
							writer.write(",");
						}else {
							writer.write("\r\n");
						}
					}
				}
				br.close();
			}
			
			writer.close();
		}catch(Exception e) {
			System.out.println(errstr);
			e.printStackTrace();
		}
	}
	public static String getnum(int i) {
    	String str="";
    	if(i<10) {
    		str="20140"+i;
    	}else if(i<13) {
    		str="2014"+i;
    	}else if(i<16) {
    		str="20150"+(i-12);
    	}
    	return str;
    }
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String loc = "dy";
		for(int i=0;i<3;i++) {
			if(i==1) {
				loc = "mig";
			}
			if(i==2) {
				loc="ctu";
			}
			fileAttribute originf = new fileAttribute("G:\\Train_Data-origin\\tl2015-2017\\deleteSymbol\\"+loc+"_raildata.csv",",","STATISTICS_DATE,OFFICE_NO,WINDOW_NO,INNER_CODE,TICKET_NO,ID_NO,ID_NAME,ID_KIND,SEX,NATION,ADDRESS,SALE_TIME,TICKET_TYPE,TRAIN_NO,BOARD_TRAIN_CODE,TRAIN_DATE,START_TIME,TRAIN_CLASS_CODE,SEAT_FEATURE,COACH_NO,SEAT_NO,SEAT_TYPE_CODE,BED_LEVEL,FROM_STATION_NAME,TO_STATION_NAME,DISTANCE,TICKET_PRICE,SALE_MODE,SEQUENCE_NO,TRADE_NO,FIRST_SEAT_TYPE");
			fileAttribute[] f = new fileAttribute[2];
			f[0] = new fileAttribute("G:\\Train_Data-origin\\CDM\\deleteSymbol\\"+loc+"_201704_201904.csv",",","STATISTICS_DATE,INNER_CODE,OFFICE_NO,WINDOW_NO,TICKET_NO,ID_KIND,ID_NO,ID_NAME,TRANSMIT_FLAG,SEX,NATION,BIRTH,ADDRESS,SUBSCRIBE,VALID_START_DATE,VALID_STOP_DATE,STATIST_DATE,UNKNOWN,OPERATER_NO,GROUP_NO,DAY_NIGHT,SALE_TIME,SUCCEED_PRINTED,TICKET_STATE,STATISTICS_FLAG,RELAY_TICKET_TYPE,TICKET_TYPE,TRAIN_NO,BOARD_TRAIN_CODE,TRAIN_DATE,START_TIME,TRAIN_CLASS_CODE,SEAT_FEATURE,COACH_NO,SEAT_NO,SEAT_TYPE_CODE,BED_LEVEL,FROM_STATION_NAME,FROM_TELE_CODE,FROM_BUREAU_CODE,FROM_SUBBUREAU_CODE,RELAY_STATION_NAME,RELAY_TELE_CODE,TO_STATION_NAME,TO_TELE_CODE,TO_SEGMENT_CODE,TO_BUREAU_CODE,TO_SUBBUREAU_CODE,ROUTE_TELECODE,DISTANCE,TICKET_PRICE,BELONG_LINE1,DISTANCE1,TICKET_PRICE1,BELONG_LINE2,DISTANCE2,TICKET_PRICE2,BELONG_LINE3,DISTANCE3,TICKET_PRICE3,BELONG_LINE4,DISTANCE4,TICKET_PRICE4,BELONG_LINE5,DISTANCE5,TICKET_PRICE5,RELAY_DISTANCE,RELAY_PRICE,ADDITION_COST,BED_RESERVE_COST,SERVICE_COST,AIR_CONDITION_PRICE,ID_NUMBER,RESERVE_UNIT,TICKET_SOURCE,SOURCE_CODE,TRAIN_AIR_CONDITION,AGENT_FEE,DISCOUNT,CHECK_SUM,CORPORATION_CODE,ORIGINAL_TICKET_TYPE,FIRST_STATION_NAME,FIRST_TELE_CODE,FIRST_BUREAU_CODE,FIRST_SUBBUREAU_CODE,LAST_STATION_NAME,LAST_TELE_CODE,LAST_BUREAU_CODE,LAST_SUBBUREAU_CODE,TOTAL_DISTANCE,TOTAL_BASE_PRICE,ONE_DATE,ONE_DISTANCE,ONE_TRAIN_CODE,FLAG1,FLAG2,BASIC_PRICE,SALE_MODE,SEQUENCE_NO,TRADE_NO,TICKET_PRICE_OBTAIN,PREFERENCE_STYLE,PREFERENCE_RATE,PREFERENCE_PRICE,FIRST_SEAT_TYPE,TEAM_ID,PURPOSE_CODE,LOCATION_CODE,AREA_CENTER_CODE");
			f[1] = new fileAttribute("G:\\Train_Data-origin\\fileAdd\\fileFileter\\"+loc+"_201404-201503.csv",",","STATISTICS_DATE,OFFICE_NO,WINDOW_NO,TICKET_NO,INNER_CODE,ID_KIND,ID_NO,ID_NAME,TRANSMIT_FLAG,SEX,NATION,BIRTH,ADDRESS,SUBSCRIBE,VALID_START_DATE,VALID_STOP_DATE,STATIST_DATE,OTHERS,OPERATER_NO,GROUP_NO,DAY_NIGHT,SALE_TIME,SUCCEED_PRINTED,TICKET_STATE,STATISTICS_FLAG,RELAY_TICKET_TYPE,TICKET_TYPE,TRAIN_NO,BOARD_TRAIN_CODE,TRAIN_DATE,START_TIME,TRAIN_CLASS_CODE,SEAT_FEATURE,COACH_NO,SEAT_NO,SEAT_TYPE_CODE,BED_LEVEL,FROM_STATION_NAME,FROM_TELE_CODE,FROM_BUREAU_CODE,FROM_SUBBUREAU_CODE,RELAY_STATION_NAME,RELAY_TELE_CODE,TO_STATION_NAME,TO_TELE_CODE,TO_SEGMENT_CODE,TO_BUREAU_CODE,TO_SUBBUREAU_CODE,ROUTE_TELECODE,DISTANCE,TICKET_PRICE,BELONG_LINE1,DISTANCE1,TICKET_PRICE1,BELONG_LINE2,DISTANCE2,TICKET_PRICE2,BELONG_LINE3,DISTANCE3,TICKET_PRICE3,BELONG_LINE4,DISTANCE4,TICKET_PRICE4,BELONG_LINE5,DISTANCE5,TICKET_PRICE5,RELAY_DISTANCE,RELAY_PRICE,ADDITION_COST,BED_RESERVE_COST,SERVICE_COST,AIR_CONDITION_PRICE,ID_NUMBER,RESERVE_UNIT,TICKET_SOURCE,SOURCE_CODE,TRAIN_AIR_CONDITION,AGENT_FEE,DISCOUNT,CHECK_SUM,CORPORATION_CODE,ORIGINAL_TICKET_TYPE,FIRST_STATION_NAME,FIRST_TELE_CODE,FIRST_BUREAU_CODE,FIRST_SUBBUREAU_CODE,LAST_STATION_NAME,LAST_TELE_CODE,LAST_BUREAU_CODE,LAST_SUBBUREAU_CODE,TOTAL_DISTANCE,TOTAL_BASE_PRICE,ONE_DATE,ONE_DISTANCE,ONE_TRAIN_CODE,TRANSMIT_FLAG,STATIST_DATE,FLAG1,FLAG2,BASIC_PRICE,SALE_MODE,SEQUENCE_NO,TRADE_NO,TICKET_PRICE_OBTAIN,PREFERENCE_STYLE,PREFERENCE_RATE,PREFERENCE_PRICE,INNER_CODE,FIRST_SEAT_TYPE,TEAM_ID,PURPOSE_CODE,LOCATION_CODE,AREA_CENTER_CODE");

			
			filesAdd(originf,f);
		}
		/*
		fileAttribute originf = new fileAttribute("G:\\Train_Data-origin\\tl2015-2017\\deleteSymbol\\fileAdd\\ctu_raildata.csv",",","STATISTICS_DATE,OFFICE_NO,WINDOW_NO,INNER_CODE,TICKET_NO,ID_NO,ID_NAME,ID_KIND,SEX,NATION,ADDRESS,SALE_TIME,TICKET_TYPE,TRAIN_NO,BOARD_TRAIN_CODE,TRAIN_DATE,START_TIME,TRAIN_CLASS_CODE,SEAT_FEATURE,COACH_NO,SEAT_NO,SEAT_TYPE_CODE,BED_LEVEL,FROM_STATION_NAME,TO_STATION_NAME,DISTANCE,TICKET_PRICE,SALE_MODE,SEQUENCE_NO,TRADE_NO,FIRST_SEAT_TYPE");
		fileAttribute[] f = new fileAttribute[1];
		f[0] = new fileAttribute("G:\\Train_Data-origin\\CDM\\deleteSymbol\\ctu_201704_201904.csv",",","STATISTICS_DATE,INNER_CODE,OFFICE_NO,WINDOW_NO,TICKET_NO,ID_KIND,ID_NO,ID_NAME,TRANSMIT_FLAG,SEX,NATION,BIRTH,ADDRESS,SUBSCRIBE,VALID_START_DATE,VALID_STOP_DATE,STATIST_DATE,UNKNOWN,OPERATER_NO,GROUP_NO,DAY_NIGHT,SALE_TIME,SUCCEED_PRINTED,TICKET_STATE,STATISTICS_FLAG,RELAY_TICKET_TYPE,TICKET_TYPE,TRAIN_NO,BOARD_TRAIN_CODE,TRAIN_DATE,START_TIME,TRAIN_CLASS_CODE,SEAT_FEATURE,COACH_NO,SEAT_NO,SEAT_TYPE_CODE,BED_LEVEL,FROM_STATION_NAME,FROM_TELE_CODE,FROM_BUREAU_CODE,FROM_SUBBUREAU_CODE,RELAY_STATION_NAME,RELAY_TELE_CODE,TO_STATION_NAME,TO_TELE_CODE,TO_SEGMENT_CODE,TO_BUREAU_CODE,TO_SUBBUREAU_CODE,ROUTE_TELECODE,DISTANCE,TICKET_PRICE,BELONG_LINE1,DISTANCE1,TICKET_PRICE1,BELONG_LINE2,DISTANCE2,TICKET_PRICE2,BELONG_LINE3,DISTANCE3,TICKET_PRICE3,BELONG_LINE4,DISTANCE4,TICKET_PRICE4,BELONG_LINE5,DISTANCE5,TICKET_PRICE5,RELAY_DISTANCE,RELAY_PRICE,ADDITION_COST,BED_RESERVE_COST,SERVICE_COST,AIR_CONDITION_PRICE,ID_NUMBER,RESERVE_UNIT,TICKET_SOURCE,SOURCE_CODE,TRAIN_AIR_CONDITION,AGENT_FEE,DISCOUNT,CHECK_SUM,CORPORATION_CODE,ORIGINAL_TICKET_TYPE,FIRST_STATION_NAME,FIRST_TELE_CODE,FIRST_BUREAU_CODE,FIRST_SUBBUREAU_CODE,LAST_STATION_NAME,LAST_TELE_CODE,LAST_BUREAU_CODE,LAST_SUBBUREAU_CODE,TOTAL_DISTANCE,TOTAL_BASE_PRICE,ONE_DATE,ONE_DISTANCE,ONE_TRAIN_CODE,FLAG1,FLAG2,BASIC_PRICE,SALE_MODE,SEQUENCE_NO,TRADE_NO,TICKET_PRICE_OBTAIN,PREFERENCE_STYLE,PREFERENCE_RATE,PREFERENCE_PRICE,FIRST_SEAT_TYPE,TEAM_ID,PURPOSE_CODE,LOCATION_CODE,AREA_CENTER_CODE");
		
		filesAdd(originf,f);
		*/
	}
}
